
version: '3.4'

x-common-env-variables: &common-env-variables
    PYTHONUNBUFFERED: 1
    

x-base-worker: &base-worker
    build:
      context: .
      dockerfile: Dockerfile
    command: python3.9 main.py
    volumes:
        - ./:/app
    networks:
      - storage_tp3_network

services:

    librarian_2:
        <<: *base-worker
        environment:
            <<: *common-env-variables
            WORKER_ID: 1
            TIMEOUT: 1
            MAX_QUEUE_SIZE: 5
            PORT: 5000
            QUORUM: 2
            ARCHITECTURE: '[{"id": 1, "name": "librarian_2", "port": 5000}, {"id": 2, "name": "librarian_3", "port": 5001}, {"id": 3, "name": "librarian_4", "port": 5002}]'
        ports:
            - "5000:5000"


    librarian_3:
        <<: *base-worker
        environment:
            <<: *common-env-variables
            WORKER_ID: 2
            TIMEOUT: 1
            MAX_QUEUE_SIZE: 5
            PORT: 5001
            QUORUM: 2
            ARCHITECTURE: '[{"id": 1, "name": "librarian_2", "port": 5000}, {"id": 2, "name": "librarian_3", "port": 5001}, {"id": 3, "name": "librarian_4", "port": 5002}]'
        ports:
            - "5001:5001"


    librarian_4:
        <<: *base-worker
        environment:
            <<: *common-env-variables
            WORKER_ID: 3
            TIMEOUT: 1
            MAX_QUEUE_SIZE: 5
            PORT: 5002
            QUORUM: 2
            ARCHITECTURE: '[{"id": 1, "name": "librarian_2", "port": 5000}, {"id": 2, "name": "librarian_3", "port": 5001}, {"id": 3, "name": "librarian_4", "port": 5002}]'
        ports:
            - "5002:5002"


networks:
    storage_tp3_network:
        ipam:
            driver: default
            config:
                - subnet: 173.105.125.0/24


