version: "3"
services:
  librarian_1:
    build:
      context: .
      dockerfile: Dockerfile
    command: main.py
    ports:
      - 5000:5000
    environment:
      - MAX_QUEUE_SIZE=5
      - PORT=5000
      - TIMEOUT=1
      - QUORUM=1
    networks:
      - tp3_network
    volumes:
      - ./:/app

  # librarian_2:
  #   build:
  #     context: .
  #   environment:
  #     - MAX_QUEUE_SIZE=5
  #     - PORT=5000
  #     - TIMEOUT=1
  #     - QUORUM=2
  #     - PORT=5000
  #   networks:
  #     - tp3_network

networks:
  storage_tp3_network:
    ipam:
      driver: default
      config:
        - subnet: 173.10.125.0/24
